import assert from 'node:assert/strict';
import worker from '../worker/index.js';
import {createLocalDb} from './local-db.mjs';
const DB=createLocalDb();
const api=(path,body)=>worker.fetch(new Request('https://garden.test/api/'+path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}),{DB});
const player={name:'Salman',character:'men',x:768,y:919,dir:'south'};
const session=await (await api('join',player)).json();
const requestId=crypto.randomUUID();
assert.equal((await api('wishes/send',{...session,requestId,message:'a'.repeat(51)})).status,400);
assert.equal((await api('wishes/send',{...session,requestId,message:'   '})).status,400);
assert.equal((await api('wishes/send',{...session,token:'bad',requestId,message:'Selamat!'})).status,401);
const message='💕'.repeat(50);
for(let i=0;i<2;i++)assert.equal((await api('wishes/send',{...session,requestId,message,name:'Fake name'})).status,200);
let list=await (await api('wishes/list',{})).json();
assert.equal(list.wishes.length,1);assert.equal(list.wishes[0].name,'Salman');assert.equal(list.wishes[0].message,message);
await api('leave',session);
const other=await (await api('join',{...player,name:'Eliza'})).json();
list=await (await api('wishes/list',other)).json();assert.equal(list.wishes.length,1);
for(let i=0;i<51;i++)await api('wishes/send',{...other,requestId:crypto.randomUUID(),message:'Bahagia selalu '+i});
const latest=await (await api('wishes/list',{latest:true,before:1})).json();assert.equal(latest.wishes.length,15);assert.equal(latest.hasMore,false);assert.equal(latest.wishes[0].message,'Bahagia selalu 50');assert.equal(latest.wishes[14].message,'Bahagia selalu 36');
const first=await (await api('wishes/list',{})).json();assert.equal(first.wishes.length,50);assert.equal(first.hasMore,true);
const second=await (await api('wishes/list',{before:first.wishes.at(-1).id})).json();assert.equal(second.wishes.length,2);assert.equal(second.hasMore,false);
assert.equal(new Set([...first.wishes,...second.wishes].map(x=>x.id)).size,52);
DB.close();console.log('PASS: shared durable wishes, author binding, 50 graphemes, validation, retry deduplication, pagination');
